version: 0.2

phases:
  install:
    commands:
      - echo Run command before build .....
  build:
    commands:
      - echo Build started ........
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/install_dependencies
    - scripts/start_server
    - scripts/stop_server
